Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
  MyBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MyBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Join ["", ["arn:aws:s3:::", !Ref MyBucket, "/*"]]
Outputs:
  WebsiteURL:
    Value:
      !Join [
        "",
        [
          "http://",
          !Ref MyBucket,
          ".s3-website-",
          !Ref "AWS::Region",
          ".amazonaws.com",
        ],
      ]
    Description: URL for the static website
